language: android
jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25

notifications:
  email:
    on_failure: never
    on_success: never

install:
  - ./gradlew core:assemble
script:
  - ./gradlew core:build

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash) -t 2422f484-2124-4578-8ee8-73e010d18a7a
